version: '3.9'
services:
  db:
   container_name: db
   image: mongo
   volumes:
     - ./data:/data/db
   ports:
      - "27017:27017"
  produits:
    image: kouririzohayr/ecommerce-app:produits.v1
    container_name: produit-service
    ports:
      - "5000:4000"
    volumes:
       - /app/node_modules
    depends_on:
     - db
  authentification:
    image: kouririzohayr/ecommerce-app:auth.v1
    container_name: auth-service
    ports:
      - "5002:4002"
    volumes:
      - /app/node_modules
    depends_on:
      - db
  commande:
    image: kouririzohayr/ecommerce-app:commande.v1
    container_name: commande-service
    ports:
      - "5001:4001"
    volumes:
      - /app/node_modules
    depends_on:
      - authentification
      - produits
      - db
  frontend:
    image: kouririzohayr/ecommerce-app:frontend.v1
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules

